import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{ type: 'autogenerated', dirName: '.' }],

  // But you can create a sidebar manually
  tutorialSidebar: [
    'intro',
    {
      type: 'category',
      label: 'Hyperfy-2',
      items: [
        'hyperfy-2/overview',
        {
          type: 'category',
          label: 'Infrastructure',
          items: [
            'hyperfy-2/infrastructure/overview',
            'hyperfy-2/infrastructure/aws-setup',
            'hyperfy-2/infrastructure/terraform-modules',
            'hyperfy-2/infrastructure/deployment',
          ],
        },
        {
          type: 'category',
          label: 'Components',
          items: [
            'hyperfy-2/components/overview',
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'AI16z',
      items: [
        'ai16z/overview',
        {
          type: 'category',
          label: 'Integrations',
          items: [
            'ai16z/integrations/hyperfy-2',
          ],
        },
        {
          type: 'category',
          label: 'Architecture',
          items: [
            'ai16z/architecture/agent-design',
            'ai16z/architecture/integration-patterns',
          ],
        },
      ],
    },
  ],
};

export default sidebars;
